[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'

[params.modules.trustindex]
  integration = "critical"

[params.modules.trustindex.csp]
  script-src = ["cdn.trustindex.io"]
  connect-src = [
    "*.trustindex.io",
    "trustindex.io"
  ]
  img-src = ["trustindex.io"]
  style-src = ["'unsafe-inline'"]
