baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-trustindex'

[module]
  # Build and serve using local mod-trustindex clone declared in the named Hugo workspace:
  workspace = "mod-trustindex.work"
  [[module.imports]]
    path = "github.com/vitabef/mod-trustindex"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"